### ISSUE TITLE
Robotboy 

### ISSUE THREAD

**Issue by Thejustice2023** [stb-gaming/standards#2]
I can't access and play this game 
![FrontEnd](https://github.com/stb-gaming/.github/assets/168474192/2dd5beb2-2483-4dee-9518-56d89642c193)

**Comment by JohnPykett1999** [comment]
Hello tumble1999 has fixed this issue you should be able to play now

**Comment by ghost** [comment]
Hello tumble1999 has fixed this issue you should be able to play now
